version: "2"
services:
  um1:
    image: ${MARIADB_CONTAINER_NAME}
    environment:
      - MARIADB_CS_POSTCFG_INPUT=
      - MARIADB_RANDOM_ROOT_PASSWORD=${MARIADB_RANDOM_ROOT_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_ALLOW_EMPTY_PASSWORD=${MARIADB_ALLOW_EMPTY_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_CS_DEBUG=${MARIADB_CS_DEBUG}
    volumes:
      - um1_etc:/usr/local/mariadb/columnstore/etc
      - um1_mysql:/usr/local/mariadb/columnstore/mysql/db
      - um1_local:/usr/local/mariadb/columnstore/local
      - ./multi_node_um1:/docker-entrypoint-initdb.d
    networks:
      mcsnet:
        ipv4_address: ${MARIADB_CS_NETWORK_SPACE}.2
        aliases:
        - columnstore_host_nm
    ports:
      - ${MARIADB_UM1_BINDING}

  um2:
    image: ${MARIADB_CONTAINER_NAME}
    environment:
      - MARIADB_CS_POSTCFG_INPUT=
      - MARIADB_DROP_LOCAL_USERS=1
    volumes:
      - um2_etc:/usr/local/mariadb/columnstore/etc
      - um2_mysql:/usr/local/mariadb/columnstore/mysql/db
      - um2_local:/usr/local/mariadb/columnstore/local
    networks:
      mcsnet:
        ipv4_address: ${MARIADB_CS_NETWORK_SPACE}.3
    ports:
      - "3307:3306"

  pm2:
    image: ${MARIADB_CONTAINER_NAME}
    environment:
      - MARIADB_CS_POSTCFG_INPUT=
      - MARIADB_CS_DEBUG=
    volumes:
      - dbroot2:/usr/local/mariadb/columnstore/data2
      - pm2_etc:/usr/local/mariadb/columnstore/etc
    networks:
      mcsnet:
        ipv4_address: ${MARIADB_CS_NETWORK_SPACE}.4

  pm1:
#    security_opt:
#      - seccomp:unconfined
    image: ${MARIADB_CONTAINER_NAME}
    environment:
      - MARIADB_CS_POSTCFG_INPUT=2\n1\nn\ny\ncolumnstore-1\n1\n2\num1\n\n\num2\n\n\n2\npm1\n\n\n1\npm2\n\n\n2\n
      - MARIADB_CS_DEBUG=
    depends_on:
      - um1
      - um2
      - pm2
    volumes:
      - dbroot1:/usr/local/mariadb/columnstore/data1
      - pm1_etc:/usr/local/mariadb/columnstore/etc
    networks:
      mcsnet:
        ipv4_address: ${MARIADB_CS_NETWORK_SPACE}.5
  zeppelin:
    hostname: zeppelin
    build: ../columnstore_zeppelin
    image: mariadb/sandboxzeppelin
    ports:
      - "8080:8080"
    depends_on:
      - um1
      - um2
      - pm1
      - pm2
    volumes:
    - ../columnstore_zeppelin/notebook:/zeppelin/notebook
    - um1_etc:/usr/local/mariadb/columnstore/etc
    networks:
      mcsnet:
        ipv4_address: ${MARIADB_CS_NETWORK_SPACE}.6

volumes:
  dbroot1:
  dbroot2:
  um1_mysql:
  um2_mysql:
  um1_etc:
  um2_etc:
  pm1_etc:
  pm2_etc:
  um1_local:
  um2_local:

networks:
  mcsnet:
    driver: bridge
    ipam:
     config:
       - subnet: ${MARIADB_CS_NETWORK_SPACE}.0/24
         gateway: ${MARIADB_CS_NETWORK_SPACE}.1
