version: "2"
services:
  um1:
    image: mariadb/columnstore:1.2-dev
    environment:
      - MARIADB_CS_POSTCFG_INPUT=
      - MARIADB_RANDOM_ROOT_PASSWORD=
      - MARIADB_ROOT_PASSWORD=
      - MARIADB_USER=dbuser
      - MARIADB_PASSWORD=dbpassword
      - MARIADB_DATABASE=mydb
    volumes:
      - um1_etc:/usr/local/mariadb/columnstore/etc
      - um1_mysql:/usr/local/mariadb/columnstore/mysql/db
      - um1_local:/usr/local/mariadb/columnstore/local
    networks:
      mcsnet:
        ipv4_address: 10.5.0.2
    ports:
      - "3306:3306"

  pm2:
    image: mariadb/columnstore:1.2-dev
    environment:
      - MARIADB_CS_POSTCFG_INPUT=
    volumes:
      - dbroot2:/usr/local/mariadb/columnstore/data2
      - pm2_etc:/usr/local/mariadb/columnstore/etc
    networks:
      mcsnet:
        ipv4_address: 10.5.0.3

  pm1:
    image: mariadb/columnstore:1.2-dev
    environment:
      - MARIADB_CS_POSTCFG_INPUT=2\n1\nn\ny\ncolumnstore-1\n1\n1\num1\n\n\n2\npm1\n\n\n1\npm2\n\n\n2\n
      - MARIADB_CS_NUM_BLOCKS_PCT=1024M
      - MARIADB_CS_TOTAL_UM_MEMORY=512M
    depends_on:
      - um1
      - pm2
    volumes:
      - dbroot1:/usr/local/mariadb/columnstore/data1
      - pm1_etc:/usr/local/mariadb/columnstore/etc
    networks:
      mcsnet:
        ipv4_address: 10.5.0.4

volumes:
  dbroot1:
  dbroot2:
  um1_mysql:
  um1_etc:
  pm1_etc:
  pm2_etc:
  um1_local:

networks:
  mcsnet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
